version: '3.6'
services:
  db:
    image: postgres:10
    restart: always
    ports:
      - '5432:5432'
    # volumes:
    #   - pgdata:/var/lib/postgresql/data

  server:
    image: node:10

# volumes:
#   pgdata: {}
