version: '3.6'
services:
  db:
    image: postgres:10
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    build: .
    env_file: .env
    ports:
      - '12000:12000'
    command: yarn start

volumes:
  pgdata: {}
